### ISSUE TITLE
Error in Keypoint Extraction

### ISSUE THREAD

**Issue by techie02** [ilvkai/view-synthesis-for-vehicles#16]
Hello,

I am trying to compute coordinates for a different car dataset resized to 256 *256. However, my keypoints are always -1. Could you please suggest a reason for such output.

@ilvkai 

Thanks

**Comment by ilvkai** [comment]
> 

Hi,
 As the key point detection method is a supervised method, directly adopting the trained network to a new dataset may not work. I suggest to re-train the key point detection network or utilizing a SOTA detection method. As far as I know, many Reid works (like https://github.com/Pirazh/Vehicle_Key_Point_Orientation_Estimation) and other key point detection works can output satisfactory results without fine-tuning.

**Comment by techie02** [comment]
Hi,
Thank you for the response and the suggested work.

**Comment by ilvkai** [comment]
Closed.
