### ISSUE TITLE
when i train 40 epoch, and test, it is very strange that the generated_images is all black. please help me, thank you very much!

### ISSUE THREAD

**Issue by junzai0215** [ilvkai/view-synthesis-for-vehicles#6]
anaconda3/envs/view-synthesis/lib/python2.7/site-packages/skimage/io/_io.py:140: UserWarning: output/VeRi-generated_images-PAGM-perceptual/0712_c004_00043620_1.jpg_0712_c010_00037775_0.jpg.png is a low contrast image

**Comment by ilvkai** [comment]
Can you provide more training details, like the training losses?

**Comment by junzai0215** [comment]
您github上的代码我下载下来没动过（包括train.py和gan/train.py），我怀疑是可视化可能有问题，然后我改了下可视化的代码，可以可视化了，但是已经训练了70个epoch了，效果还是很差











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ilvkai/view-synthesis-for-vehicles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上6:41
***@***.***&gt;;
抄送:&nbsp;"Wenjun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ilvkai/view-synthesis-for-vehicles] when i train 40 epoch, and test, it is very strange that the generated_images is all black. please help me, thank you very much! (#6)





 
Can you provide more training details, like the training losses?

**Comment by ilvkai** [comment]
Before uploading the repo, we have carefully checked the codes. We are sure that the code is reproducible. However, since the code was written 2 years ago, several dependent python packages have changed, which may heavily influence the experiment reproduction. I suggest you pay attention to the code related to Pillow.

**Comment by junzai0215** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ilvkai/view-synthesis-for-vehicles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月15日(星期六) 上午10:59
***@***.***&gt;;
抄送:&nbsp;"Wenjun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ilvkai/view-synthesis-for-vehicles] when i train 40 epoch, and test, it is very strange that the generated_images is all black. please help me, thank you very much! (#6)





 
Before uploading the repo, we have carefully checked the codes. We are sure that the code is reproducible. However, since the code was written 2 years ago, several dependent python packages have changed, which may heavily influence the experiment reproduction. I suggest you pay attention to the code related to Pillow.
